import { secureRandomInt, shuffleArray } from './secureRandom';

export const WORD_POOL = [
  // Animals
  "LION", "TIGER", "BEAR", "ELEPHANT", "GIRAFFE", "ZEBRA", "MONKEY", "PANDA", "KOALA", "KANGAROO",
  "PENGUIN", "DOLPHIN", "WHALE", "SHARK", "OCTOPUS", "EAGLE", "HAWK", "OWL", "PARROT", "FLAMINGO",
  "RABBIT", "HAMSTER", "TURTLE", "FROG", "SNAKE", "LIZARD", "CROCODILE", "HIPPO", "RHINO", "WOLF",
  "FOX", "DEER", "MOOSE", "BUFFALO", "HORSE", "COW", "PIG", "SHEEP", "GOAT", "CHICKEN",
  
  // Fruits & Veggies
  "APPLE", "BANANA", "ORANGE", "GRAPE", "LEMON", "LIME", "PEACH", "PEAR", "PLUM", "CHERRY",
  "STRAWBERRY", "BLUEBERRY", "RASPBERRY", "MANGO", "PINEAPPLE", "KIWI", "MELON", "PAPAYA", "FIG", "DATE",
  "CARROT", "POTATO", "TOMATO", "ONION", "PEPPER", "CORN", "PEAS", "BEANS", "BROCCOLI", "SPINACH",
  "LETTUCE", "CUCUMBER", "ZUCCHINI", "PUMPKIN", "RADISH", "CELERY", "GARLIC", "GINGER", "MUSHROOM", "OLIVE",
  
  // Colors
  "RED", "ORANGE", "YELLOW", "GREEN", "BLUE", "PURPLE", "PINK", "BROWN", "BLACK", "WHITE",
  "GRAY", "SILVER", "GOLD", "TEAL", "TURQUOISE", "INDIGO", "VIOLET", "MAGENTA", "CYAN", "BEIGE",
  "MAROON", "NAVY", "OLIVE", "CORAL", "SALMON", "LAVENDER", "CRIMSON", "AZURE", "IVORY", "AMBER",
  
  // Space
  "SUN", "MOON", "STAR", "PLANET", "MERCURY", "VENUS", "EARTH", "MARS", "JUPITER", "SATURN",
  "URANUS", "NEPTUNE", "PLUTO", "COMET", "ASTEROID", "METEOR", "GALAXY", "UNIVERSE", "NEBULA", "ORBIT",
  "ROCKET", "ASTRONAUT", "TELESCOPE", "SATELLITE", "ECLIPSE", "GRAVITY", "CONSTELATION", "SPACE", "SKY", "ALIEN",
  
  // Sports
  "SOCCER", "BASKETBALL", "BASEBALL", "FOOTBALL", "TENNIS", "GOLF", "HOCKEY", "VOLLEYBALL", "RUGBY", "CRICKET",
  "SWIMMING", "RUNNING", "JUMPING", "CYCLING", "SKATING", "SKIING", "SURFING", "KARATE", "BOXING", "WRESTLING",
  "GYMNASTICS", "DANCE", "YOGA", "PILATES", "HIKING", "CAMPING", "FISHING", "HUNTING", "BOWLING", "ARCHERY",
  
  // School
  "PENCIL", "PEN", "ERASER", "RULER", "PAPER", "BOOK", "NOTEBOOK", "DESK", "CHAIR", "BOARD",
  "TEACHER", "STUDENT", "CLASS", "SCHOOL", "HOMEWORK", "TEST", "EXAM", "GRADE", "SUBJECT", "MATH",
  "SCIENCE", "HISTORY", "ART", "MUSIC", "GYM", "RECESS", "LUNCH", "FRIEND", "LEARN", "STUDY",
  
  // Nature
  "TREE", "FLOWER", "GRASS", "LEAF", "BRANCH", "ROOT", "FOREST", "JUNGLE", "DESERT", "OCEAN",
  "RIVER", "LAKE", "POND", "STREAM", "MOUNTAIN", "HILL", "VALLEY", "CANYON", "ISLAND", "BEACH",
  "SAND", "ROCK", "STONE", "DIRT", "MUD", "RAIN", "SNOW", "WIND", "STORM", "CLOUD",

  // Christian
  "JESUS", "CHRIST", "BIBLE", "FAITH", "HOPE", "LOVE", "PRAYER", "CHURCH", "CROSS", "GOSPEL",
  "SPIRIT", "GRACE", "MERCY", "SAVIOR", "LORD", "GOD", "ANGEL", "HEAVEN", "MIRACLE", "DISCIPLE",
  "APOSTLE", "PSALM", "PROPHET", "HOLY", "GLORY", "WORSHIP", "PRAISE", "BLESSING", "REDEMPTION", "SALVATION",

  // Emotions
  "HAPPY", "SAD", "ANGRY", "EXCITED", "SCARED", "BORED", "TIRED", "CALM", "PROUD", "SHY",
  "BRAVE", "CONFUSED", "JEALOUS", "LONELY", "SURPRISED", "NERVOUS", "GRATEFUL", "JOYFUL", "HOPEFUL", "ANNOYED",
  "PEACEFUL", "SILLY", "CURIOUS", "DISAPPOINTED", "FRUSTRATED", "GUILTY", "EMBARRASSED", "CONFIDENT", "RELAXED", "LOVED",

  // Oxymorons
  "BITTERSWEET", "OPEN SECRET", "LIVING DEAD", "JUMBO SHRIMP", "VIRTUAL REALITY", "OLD NEWS", "EXACT ESTIMATE", "SMALL CROWD", "ACT NATURALLY", "ONLY CHOICE",
  "RANDOM ORDER", "ORIGINAL COPY", "DEFINITELY MAYBE", "AWFULLY GOOD", "PRETTY UGLY", "FOUND MISSING", "SAME DIFFERENCE", "CRASH LANDING", "FREEZER BURN", "ROLLING STOP",
  "SILENT SCREAM", "CIVIL WAR", "WORKING VACATION", "ALONE TOGETHER", "SWEET SORROW", "TERRIBLY GOOD", "BIG BABY", "HEAVY LIGHT", "SERIOUS FUN", "WISE FOOL",

  // Texas
  "HOWDY", "YALL", "COWBOY", "RODEO", "ALAMO", "LONGHORN", "OIL", "RANCH", "BBQ", "AUSTIN",
  "HOUSTON", "DALLAS", "TEXAS", "LONE STAR", "BLUEBONNET", "ARMADILLO", "BRISKET", "BOOTS", "SPURS", "WRANGLER",
  "CATTLE", "FRONTIER", "SOUTHERN", "PECAN", "COTTON", "FIDDLE", "COUNTRY", "GALVESTON", "RIO GRANDE", "CHAPARRAL",

  // BBQ
  "RIBS", "PULLED PORK", "SAUSAGE", "BURNT ENDS", "SMOKE RING", "GRILL", "CHARCOAL", "HICKORY", "MESQUITE", "SAUCE",
  "DRY RUB", "COLESLAW", "BAKED BEANS", "CORNBREAD", "PITMASTER", "LOW AND SLOW", "MARINADE", "GLAZE", "SKEWER", "KABOB",
  "STEAK", "BURGER", "HOT DOG", "WINGS", "TENDER", "JUICY", "SPICY", "SMOKER", "PELLET", "PORK BUTT",

  // Philosophy
  "LOGIC", "ETHICS", "MORAL", "TRUTH", "MIND", "SOUL", "REASON", "KNOWLEDGE", "BEING", "EXISTENCE",
  "REALITY", "WISDOM", "VIRTUE", "JUSTICE", "LIBERTY", "FREE WILL", "STOICISM", "PLATO", "SOCRATES", "KANT",
  "NIETZSCHE", "DUALISM", "MONISM", "IDEALISM", "REALISM", "EGO", "SELF", "CONSCIOUSNESS", "METAPHYSICS", "EPISTEMOLOGY",

  // Biology
  "CELL", "DNA", "RNA", "GENE", "MITOSIS", "MEIOSIS", "ORGANISM", "SPECIES", "EVOLUTION", "ECOLOGY",
  "PHOTOSYNTHESIS", "RESPIRATION", "BACTERIA", "VIRUS", "FUNGUS", "PLANT", "ANIMAL", "TISSUE", "ORGAN", "SYSTEM",
  "MEMBRANE", "NUCLEUS", "CYTOPLASM", "PROTEIN", "ENZYME", "GENETICS", "HEREDITY", "MUTATION", "ADAPTATION", "BIOME",

  // General Science
  "ATOM", "MOLECULE", "PROTON", "NEUTRON", "ELECTRON", "CHEMISTRY", "PHYSICS", "ENERGY", "FORCE", "MOTION",
  "VELOCITY", "FRICTION", "MAGNETISM", "ELECTRICITY", "CIRCUIT", "VOLTAGE", "MATTER", "SOLID", "LIQUID", "GAS",
  "PLASMA", "EXPERIMENT", "HYPOTHESIS", "THEORY", "VARIABLE", "OBSERVATION", "DATA", "LABORATORY", "FORMULA", "DENSITY",

  // Chemistry
  "ELEMENT", "COMPOUND", "MIXTURE", "SOLUTION", "ACID", "BASE", "PH SCALE", "REACTION", "BOND", "ION",
  "ISOTOPE", "PERIODIC TABLE", "METAL", "NONMETAL", "GAS", "OXYGEN", "HYDROGEN", "CARBON", "NITROGEN", "HELIUM",
  "GOLD", "SILVER", "IRON", "COPPER", "ZINC", "CATALYST", "POLYMER", "SOLVENT", "SOLUTE", "PRECIPITATE"
];

export function getRandomDefaultWords(min = 8, max = 15): string {
  const count = secureRandomInt(min, max + 1);
  const shuffled = shuffleArray([...WORD_POOL]);
  return shuffled.slice(0, count).join(',');
}
